import { useState } from "react";
import { Link } from "react-router-dom";
import { calculateUps, titleSpecs } from "@/lib/catalog";
import { useProducts } from "@/hooks/useProducts";
import { ProductCard } from "./ProductCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export default function UpsCalculator() {
  const [load,setLoad]=useState(300);const [hours,setHours]=useState(2);const [efficiency,setEfficiency]=useState(85);const [usable,setUsable]=useState(80);
  const result=calculateUps(load,hours,efficiency/100,usable/100);const {products}=useProducts({activeOnly:true});
  const suggested=products.filter(p=>{if(p.category!=="ups" || p.stock<=0 || !result)return false;const power=titleSpecs(p).power;const match=power?.match(/(\d+(?:\.\d+)?)\s*(k\s?w|كيلو\s*واط|واط|W|kVA)/i);if(!match)return false;const value=Number(match[1])*(/k|كيلو/i.test(match[2])?1000:1);return /kVA/i.test(match[2]) ? value>=result.minimumVa : value>=result.minimumWatts;}).slice(0,4);
  return <div className="mx-auto max-w-5xl space-y-6 px-4 py-10"><h1 className="text-3xl font-bold">حاسبة اختيار UPS</h1><p className="text-sm leading-7 text-muted-foreground">تقدير أولي مع هامش قدرة 25% ومعامل قدرة مفترض 0.8. يعتمد وقت التشغيل الفعلي على كفاءة الجهاز، نوع البطارية وعمرها وحدود التفريغ. راجع قدرة الخرج بالواط ومنحنى التشغيل قبل الشراء.</p><div className="grid gap-4 rounded-2xl border bg-card p-6 sm:grid-cols-2">{[{id:"ups-load",label:"مجموع الأحمال (واط)",value:load,set:setLoad,max:100000},{id:"ups-hours",label:"وقت التشغيل المطلوب (ساعة)",value:hours,set:setHours,max:168},{id:"ups-efficiency",label:"كفاءة التحويل (%)",value:efficiency,set:setEfficiency,max:100},{id:"ups-usable",label:"نسبة الطاقة القابلة للاستخدام (%)",value:usable,set:setUsable,max:100}].map(x=><div key={x.id}><Label htmlFor={x.id}>{x.label}</Label><Input id={x.id} dir="ltr" type="number" min={0.01} max={x.max} step="any" value={x.value} onChange={e=>x.set(Number(e.target.value))} /></div>)}</div>{result ? <section aria-live="polite" className="grid gap-4 sm:grid-cols-3">{[{label:"قدرة خرج UPS المقترحة على الأقل",value:`${result.minimumWatts} W`},{label:"القدرة الظاهرية التقديرية",value:`${result.minimumVa} VA`},{label:"طاقة البطارية الاسمية المطلوبة",value:`${result.batteryWh} Wh`}].map(x=><div key={x.label} className="surface-card p-5"><p>{x.label}</p><p dir="ltr" className="mt-2 text-2xl font-bold text-primary">{x.value}</p></div>)}</section> : <p role="alert" className="text-destructive">أدخل أرقامًا موجبة وكفاءة ونسبة استخدام لا تتجاوزان 100%.</p>}<div className="flex flex-wrap gap-3"><Button asChild><Link to="/quote">اطلب تصميمًا مناسبًا لأحمالك</Link></Button><Button asChild variant="outline"><Link to="/products?category=ups&stock=in">تصفح أجهزة UPS المتوفرة</Link></Button><Button asChild variant="outline"><Link to="/products?category=solar&stock=in">بطاريات وعواكس الطاقة الشمسية</Link></Button></div>{!!suggested.length && <section><h2 className="mb-3 text-xl font-bold">أجهزة تستحق المراجعة بحسب القدرة المذكورة</h2><p className="mb-4 text-sm text-muted-foreground">هذه خيارات أولية؛ لم يتم تأكيد توافق البطاريات أو وقت التشغيل معها.</p><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{suggested.map(p=><ProductCard key={p.id} product={p} />)}</div></section>}</div>;
}
