// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/search-products.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the store catalog by name (Arabic, English, or data name), SKU or brand. Prices shown follow the signed-in user's pricing tier.",
  inputSchema: {
    query: z.string().trim().nullable().describe("Free text to match against product names, SKU or brand. Null lists recent products."),
    brand: z.string().trim().nullable().describe("Exact brand name filter, or null."),
    in_stock_only: z.boolean().nullable().describe("When true, only products with stock above zero."),
    limit: z.number().int().min(1).max(100).nullable().describe("Maximum rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ query, brand, in_stock_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("products").select("id, sku, name_ar, name_en, name_data, brand, subcategory, price_iqd, price_wholesale_iqd, price_dealer_iqd, stock, is_active, image_url").eq("is_active", true).limit(limit ?? 25);
    if (query) {
      const like = `%${query}%`;
      q = q.or(`name_ar.ilike.${like},name_en.ilike.${like},name_data.ilike.${like},sku.ilike.${like},brand.ilike.${like}`);
    }
    if (brand) q = q.eq("brand", brand);
    if (in_stock_only) q = q.gt("stock", 0);
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    const products = (data ?? []).map((p) => ({
      id: p.id,
      sku: p.sku ?? null,
      nameAr: p.name_ar,
      nameEn: p.name_en,
      nameData: p.name_data ?? null,
      brand: p.brand ?? null,
      subcategory: p.subcategory ?? null,
      priceIqd: p.price_iqd,
      priceWholesaleIqd: p.price_wholesale_iqd,
      priceDealerIqd: p.price_dealer_iqd,
      stock: p.stock,
      imageUrl: p.image_url ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch one product with full details (descriptions, prices, stock, datasheet) by its id.",
  inputSchema: { id: z2.string().uuid().describe("Product id.") },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("products").select("*").eq("id", id).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2(`No product found with id ${id}`);
    const product = {
      id: data.id,
      sku: data.sku ?? null,
      nameAr: data.name_ar,
      nameEn: data.name_en,
      nameData: data.name_data ?? null,
      descAr: data.desc_ar ?? null,
      descEn: data.desc_en ?? null,
      brand: data.brand ?? null,
      subcategory: data.subcategory ?? null,
      categoryId: data.category_id ?? null,
      priceIqd: data.price_iqd,
      priceWholesaleIqd: data.price_wholesale_iqd,
      priceDealerIqd: data.price_dealer_iqd,
      stock: data.stock,
      isActive: data.is_active,
      imageUrl: data.image_url ?? null,
      datasheetUrl: data.datasheet_url ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-catalog-taxonomy.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.1";
var list_catalog_taxonomy_default = defineTool3({
  name: "list_catalog_taxonomy",
  title: "List categories and brands",
  description: "List all store categories, subcategories and brands, useful before filtering a product search.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const [categories, subcategories, brands] = await Promise.all([
      supabase.from("categories").select("id, name_ar, name_en, slug"),
      supabase.from("subcategories").select("id, category_id, name_ar, name_en"),
      supabase.from("brands").select("id, name, logo_url")
    ]);
    const firstError = categories.error ?? subcategories.error ?? brands.error;
    if (firstError) throw new ToolError3(firstError.message);
    const taxonomy = {
      categories: (categories.data ?? []).map((c) => ({
        id: c.id,
        nameAr: c.name_ar,
        nameEn: c.name_en,
        slug: c.slug ?? null
      })),
      subcategories: (subcategories.data ?? []).map((s) => ({
        id: s.id,
        categoryId: s.category_id ?? null,
        nameAr: s.name_ar,
        nameEn: s.name_en
      })),
      brands: (brands.data ?? []).map((b) => ({
        id: b.id,
        name: b.name,
        logoUrl: b.logo_url ?? null
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(taxonomy, null, 2) }],
      structuredContent: taxonomy
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the orders visible to the signed-in user, newest first, with optional status filter.",
  inputSchema: {
    status: z3.string().trim().nullable().describe("Order status filter (e.g. pending, confirmed), or null for all."),
    limit: z3.number().int().min(1).max(100).nullable().describe("Maximum orders to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("orders").select("id, order_no, status, total_iqd, customer_name, customer_phone, customer_city, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) throw new ToolError4(error.message);
    const orders = (data ?? []).map((o) => ({
      id: o.id,
      orderNo: o.order_no,
      status: o.status,
      totalIqd: o.total_iqd,
      customerName: o.customer_name,
      customerPhone: o.customer_phone,
      customerCity: o.customer_city ?? null,
      createdAt: o.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(orders, null, 2) }],
      structuredContent: { orders }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_order_default = defineTool5({
  name: "get_order",
  title: "Get order with items",
  description: "Fetch one order the signed-in user may see, including its line items.",
  inputSchema: { id: z4.string().uuid().describe("Order id.") },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select("*").eq("id", id).maybeSingle();
    if (error) throw new ToolError5(error.message);
    if (!data) throw new ToolError5(`No order visible with id ${id}`);
    const { data: items, error: itemsError } = await supabase.from("order_items").select("*").eq("order_id", id);
    if (itemsError) throw new ToolError5(itemsError.message);
    const order = {
      id: data.id,
      orderNo: data.order_no,
      status: data.status,
      totalIqd: data.total_iqd,
      customerName: data.customer_name,
      customerPhone: data.customer_phone,
      customerCity: data.customer_city ?? null,
      customerAddress: data.customer_address ?? null,
      notes: data.notes ?? null,
      createdAt: data.created_at,
      items: (items ?? []).map((i) => {
        const row = i;
        return {
          id: String(row.id),
          productId: row.product_id == null ? null : String(row.product_id),
          name: row.name_en == null ? row.name_ar == null ? null : String(row.name_ar) : String(row.name_en),
          quantity: Number(row.qty ?? row.quantity ?? 0),
          unitPriceIqd: Number(row.unit_price_iqd ?? row.price_iqd ?? 0)
        };
      })
    };
    return {
      content: [{ type: "text", text: JSON.stringify(order, null, 2) }],
      structuredContent: { order }
    };
  }
});

// src/lib/mcp/tools/create-quote-request.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_quote_request_default = defineTool6({
  name: "create_quote_request",
  title: "Create quote request",
  description: "Submit a price quote request to the sales team on behalf of the signed-in user.",
  inputSchema: {
    full_name: z5.string().trim().min(1).describe("Contact full name."),
    phone: z5.string().trim().min(1).describe("Contact phone number."),
    email: z5.string().trim().nullable().describe("Contact email, or null."),
    company: z5.string().trim().nullable().describe("Company name, or null."),
    product_id: z5.string().uuid().nullable().describe("Related product id, or null."),
    product_name: z5.string().trim().nullable().describe("Product name if no id is known, or null."),
    message: z5.string().trim().nullable().describe("Details of what is needed, or null.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError6("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("quote_requests").insert({
      full_name: input.full_name,
      phone: input.phone,
      email: input.email ?? null,
      company: input.company ?? null,
      product_id: input.product_id ?? null,
      product_name: input.product_name ?? null,
      message: input.message ?? null
    }).select("id, full_name, phone, status, created_at").single();
    if (error) throw new ToolError6(error.message);
    const quote = {
      id: data.id,
      fullName: data.full_name,
      phone: data.phone,
      status: data.status,
      createdAt: data.created_at
    };
    return {
      content: [{ type: "text", text: `Quote request created (${quote.id}).` }],
      structuredContent: { quote }
    };
  }
});

// src/lib/mcp/tools/list-content.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_content_default = defineTool7({
  name: "list_content",
  title: "List blog posts or projects",
  description: "List published blog posts or completed projects from the website.",
  inputSchema: {
    kind: z6.enum(["blog", "projects"]).describe("Which content to list."),
    limit: z6.number().int().min(1).max(50).nullable().describe("Maximum rows (default 10).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ kind, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError7("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const take = limit ?? 10;
    if (kind === "projects") {
      const { data: data2, error: error2 } = await supabase.from("projects").select("id, slug, title_ar, title_en, summary_ar, summary_en, location, client, completed_at, is_published").eq("is_published", true).order("sort", { ascending: true }).limit(take);
      if (error2) throw new ToolError7(error2.message);
      const items2 = (data2 ?? []).map((p) => ({
        id: p.id,
        slug: p.slug,
        titleAr: p.title_ar,
        titleEn: p.title_en,
        summaryAr: p.summary_ar ?? null,
        summaryEn: p.summary_en ?? null,
        location: p.location ?? null,
        client: p.client ?? null,
        completedAt: p.completed_at ?? null
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(items2, null, 2) }],
        structuredContent: { projects: items2 }
      };
    }
    const { data, error } = await supabase.from("blog_posts").select("*").order("created_at", { ascending: false }).limit(take);
    if (error) throw new ToolError7(error.message);
    const items = (data ?? []).map((row) => {
      const p = row;
      return {
        id: String(p.id),
        slug: p.slug == null ? null : String(p.slug),
        titleAr: p.title_ar == null ? null : String(p.title_ar),
        titleEn: p.title_en == null ? null : String(p.title_en),
        excerptAr: p.excerpt_ar == null ? null : String(p.excerpt_ar),
        excerptEn: p.excerpt_en == null ? null : String(p.excerpt_en),
        createdAt: p.created_at == null ? null : String(p.created_at)
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { posts: items }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ecbbhathvpxrgvfztzeu";
var mcp_default = defineMcp({
  name: "ufuk-al-basra",
  title: "UFUK AL-Basra",
  version: "0.1.0",
  instructions: "Tools for the UFUK AL-Basra store. Use `search_products` and `get_product` for the catalog, `list_catalog_taxonomy` for categories and brands, `list_my_orders` and `get_order` for the signed-in user's orders, `create_quote_request` to ask sales for a price, and `list_content` for blog posts and projects. All data access runs as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_products_default,
    get_product_default,
    list_catalog_taxonomy_default,
    list_my_orders_default,
    get_order_default,
    create_quote_request_default,
    list_content_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
