// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/search-products.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search the store catalog by name (Arabic, English, or data name), SKU or brand. Prices shown follow the signed-in user's pricing tier.",
  inputSchema: {
    query: z.string().trim().nullable().describe("Free text to match against product names, SKU or brand. Null lists recent products."),
    brand: z.string().trim().nullable().describe("Exact brand name filter, or null."),
    in_stock_only: z.boolean().nullable().describe("When true, only products with stock above zero."),
    limit: z.number().int().min(1).max(100).nullable().describe("Maximum rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ query, brand, in_stock_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("products").select("id, sku, name_ar, name_en, name_data, brand, subcategory, price_iqd, price_wholesale_iqd, price_dealer_iqd, stock, is_active, image_url").eq("is_active", true).limit(limit ?? 25);
    if (query) {
      const like = `%${query}%`;
      q = q.or(`name_ar.ilike.${like},name_en.ilike.${like},name_data.ilike.${like},sku.ilike.${like},brand.ilike.${like}`);
    }
    if (brand) q = q.eq("brand", brand);
    if (in_stock_only) q = q.gt("stock", 0);
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    const products = (data ?? []).map((p) => ({
      id: p.id,
      sku: p.sku ?? null,
      nameAr: p.name_ar,
      nameEn: p.name_en,
      nameData: p.name_data ?? null,
      brand: p.brand ?? null,
      subcategory: p.subcategory ?? null,
      priceIqd: p.price_iqd,
      priceWholesaleIqd: p.price_wholesale_iqd,
      priceDealerIqd: p.price_dealer_iqd,
      stock: p.stock,
      imageUrl: p.image_url ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch one product with full details (descriptions, prices, stock, datasheet) by its id.",
  inputSchema: { id: z2.string().uuid().describe("Product id.") },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("products").select("*").eq("id", id).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2(`No product found with id ${id}`);
    const product = {
      id: data.id,
      sku: data.sku ?? null,
      nameAr: data.name_ar,
      nameEn: data.name_en,
      nameData: data.name_data ?? null,
      descAr: data.desc_ar ?? null,
      descEn: data.desc_en ?? null,
      brand: data.brand ?? null,
      subcategory: data.subcategory ?? null,
      categoryId: data.category_id ?? null,
      priceIqd: data.price_iqd,
      priceWholesaleIqd: data.price_wholesale_iqd,
      priceDealerIqd: data.price_dealer_iqd,
      stock: data.stock,
      isActive: data.is_active,
      imageUrl: data.image_url ?? null,
      datasheetUrl: data.datasheet_url ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/list-catalog-taxonomy.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.1";
var list_catalog_taxonomy_default = defineTool3({
  name: "list_catalog_taxonomy",
  title: "List categories and brands",
  description: "List all store categories, subcategories and brands, useful before filtering a product search.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const [categories, subcategories, brands] = await Promise.all([
      supabase.from("categories").select("id, key, name_ar, name_en").order("sort", { ascending: true }),
      supabase.from("subcategories").select("id, category_id, name_ar, name_en"),
      supabase.from("brands").select("id, name, logo_url")
    ]);
    const firstError = categories.error ?? subcategories.error ?? brands.error;
    if (firstError) throw new ToolError3(firstError.message);
    const taxonomy = {
      categories: (categories.data ?? []).map((c) => ({
        id: c.id,
        nameAr: c.name_ar,
        nameEn: c.name_en,
        key: c.key
      })),
      subcategories: (subcategories.data ?? []).map((s) => ({
        id: s.id,
        categoryId: s.category_id ?? null,
        nameAr: s.name_ar,
        nameEn: s.name_en
      })),
      brands: (brands.data ?? []).map((b) => ({
        id: b.id,
        name: b.name,
        logoUrl: b.logo_url ?? null
      }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(taxonomy, null, 2) }],
      structuredContent: taxonomy
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool4({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the orders visible to the signed-in user, newest first, with optional status filter.",
  inputSchema: {
    status: z3.string().trim().nullable().describe("Order status filter (e.g. pending, confirmed), or null for all."),
    limit: z3.number().int().min(1).max(100).nullable().describe("Maximum orders to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("orders").select("id, order_no, status, total_iqd, customer_name, customer_phone, customer_city, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) throw new ToolError4(error.message);
    const orders = (data ?? []).map((o) => ({
      id: o.id,
      orderNo: o.order_no,
      status: o.status,
      totalIqd: o.total_iqd,
      customerName: o.customer_name,
      customerPhone: o.customer_phone,
      customerCity: o.customer_city ?? null,
      createdAt: o.created_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(orders, null, 2) }],
      structuredContent: { orders }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_order_default = defineTool5({
  name: "get_order",
  title: "Get order with items",
  description: "Fetch one order the signed-in user may see, including its line items.",
  inputSchema: { id: z4.string().uuid().describe("Order id.") },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError5("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select("*").eq("id", id).maybeSingle();
    if (error) throw new ToolError5(error.message);
    if (!data) throw new ToolError5(`No order visible with id ${id}`);
    const { data: items, error: itemsError } = await supabase.from("order_items").select("*").eq("order_id", id);
    if (itemsError) throw new ToolError5(itemsError.message);
    const order = {
      id: data.id,
      orderNo: data.order_no,
      status: data.status,
      totalIqd: data.total_iqd,
      customerName: data.customer_name,
      customerPhone: data.customer_phone,
      customerCity: data.customer_city ?? null,
      customerAddress: data.customer_address ?? null,
      notes: data.notes ?? null,
      createdAt: data.created_at,
      items: (items ?? []).map((i) => {
        const row = i;
        return {
          id: String(row.id),
          productId: row.product_id == null ? null : String(row.product_id),
          name: row.name_en == null ? row.name_ar == null ? null : String(row.name_ar) : String(row.name_en),
          quantity: Number(row.qty ?? row.quantity ?? 0),
          unitPriceIqd: Number(row.unit_price_iqd ?? row.price_iqd ?? 0)
        };
      })
    };
    return {
      content: [{ type: "text", text: JSON.stringify(order, null, 2) }],
      structuredContent: { order }
    };
  }
});

// src/lib/mcp/tools/create-quote-request.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_quote_request_default = defineTool6({
  name: "create_quote_request",
  title: "Create quote request",
  description: "Submit a price quote request to the sales team on behalf of the signed-in user.",
  inputSchema: {
    full_name: z5.string().trim().min(1).describe("Contact full name."),
    phone: z5.string().trim().min(1).describe("Contact phone number."),
    email: z5.string().trim().nullable().describe("Contact email, or null."),
    company: z5.string().trim().nullable().describe("Company name, or null."),
    product_id: z5.string().uuid().nullable().describe("Related product id, or null."),
    product_name: z5.string().trim().nullable().describe("Product name if no id is known, or null."),
    message: z5.string().trim().nullable().describe("Details of what is needed, or null.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError6("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("quote_requests").insert({
      full_name: input.full_name,
      phone: input.phone,
      email: input.email ?? null,
      company: input.company ?? null,
      product_id: input.product_id ?? null,
      product_name: input.product_name ?? null,
      message: input.message ?? null
    }).select("id, full_name, phone, status, created_at").single();
    if (error) throw new ToolError6(error.message);
    const quote = {
      id: data.id,
      fullName: data.full_name,
      phone: data.phone,
      status: data.status,
      createdAt: data.created_at
    };
    return {
      content: [{ type: "text", text: `Quote request created (${quote.id}).` }],
      structuredContent: { quote }
    };
  }
});

// src/lib/mcp/tools/list-content.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_content_default = defineTool7({
  name: "list_content",
  title: "List blog posts or projects",
  description: "List published blog posts or completed projects from the website.",
  inputSchema: {
    kind: z6.enum(["blog", "projects"]).describe("Which content to list."),
    limit: z6.number().int().min(1).max(50).nullable().describe("Maximum rows (default 10).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ kind, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError7("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const take = limit ?? 10;
    if (kind === "projects") {
      const { data: data2, error: error2 } = await supabase.from("projects").select("id, slug, title_ar, title_en, summary_ar, summary_en, location, client, completed_at, is_published").eq("is_published", true).order("sort", { ascending: true }).limit(take);
      if (error2) throw new ToolError7(error2.message);
      const items2 = (data2 ?? []).map((p) => ({
        id: p.id,
        slug: p.slug,
        titleAr: p.title_ar,
        titleEn: p.title_en,
        summaryAr: p.summary_ar ?? null,
        summaryEn: p.summary_en ?? null,
        location: p.location ?? null,
        client: p.client ?? null,
        completedAt: p.completed_at ?? null
      }));
      return {
        content: [{ type: "text", text: JSON.stringify(items2, null, 2) }],
        structuredContent: { projects: items2 }
      };
    }
    const { data, error } = await supabase.from("blog_posts").select("*").order("created_at", { ascending: false }).limit(take);
    if (error) throw new ToolError7(error.message);
    const items = (data ?? []).map((row) => {
      const p = row;
      return {
        id: String(p.id),
        slug: p.slug == null ? null : String(p.slug),
        titleAr: p.title_ar == null ? null : String(p.title_ar),
        titleEn: p.title_en == null ? null : String(p.title_en),
        excerptAr: p.excerpt_ar == null ? null : String(p.excerpt_ar),
        excerptEn: p.excerpt_en == null ? null : String(p.excerpt_en),
        createdAt: p.created_at == null ? null : String(p.created_at)
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { posts: items }
    };
  }
});

// src/lib/mcp/tools/list-all-products.ts
import { defineTool as defineTool8, ToolError as ToolError9 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z8 } from "npm:zod@^3.25.76";

// src/lib/mcp/admin.ts
import { ToolError as ToolError8 } from "npm:@lovable.dev/mcp-js@3.0.1";
async function requireAdmin(ctx) {
  if (!ctx.isAuthenticated()) throw new ToolError8("Not authenticated");
  const userId = ctx.getUserId();
  if (!userId) throw new ToolError8("Admin role required");
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.rpc("has_role", { _user_id: userId, _role: "admin" });
  if (error) throw new ToolError8(`Could not verify admin role: ${error.message}`);
  if (data !== true) throw new ToolError8("Admin role required");
  return { supabase, userId };
}
function compact(input) {
  return Object.fromEntries(Object.entries(input).filter(([, v]) => v !== void 0));
}
function assertHasChanges(patch) {
  if (Object.keys(patch).length === 0) throw new ToolError8("Provide at least one field to update");
}
function slugify(input) {
  return input.toLowerCase().trim().replace(/[^a-z0-9\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "");
}
function jsonResult(summary, structured) {
  return {
    content: [{ type: "text", text: `${summary}
${JSON.stringify(structured, null, 2)}` }],
    structuredContent: structured
  };
}
function notFound(kind, id) {
  throw new ToolError8(`No ${kind} found with id ${id}`);
}

// src/lib/mcp/products.ts
import { z as z7 } from "npm:zod@^3.25.76";
var iqd = z7.number().int().min(0);
var text = z7.string().trim();
var productFields = {
  name_en: text.min(1).optional().describe("English name. Defaults to name_ar on create."),
  name_data: text.nullable().optional().describe("Internal/data name used by stock imports, or null."),
  desc_ar: text.nullable().optional().describe("Arabic description, or null."),
  desc_en: text.nullable().optional().describe("English description, or null."),
  sku: text.nullable().optional().describe("SKU, or null."),
  brand: text.nullable().optional().describe("Brand name (as in list_catalog_taxonomy), or null."),
  category_id: z7.string().uuid().nullable().optional().describe("Category id, or null."),
  subcategory: text.nullable().optional().describe("Subcategory name(s), comma-separated, or null."),
  price_iqd: iqd.optional().describe("Retail price in IQD (>= 0)."),
  price_wholesale_iqd: iqd.optional().describe("Wholesale price in IQD (>= 0)."),
  price_dealer_iqd: iqd.optional().describe("Dealer price in IQD (>= 0)."),
  stock: z7.number().int().min(0).optional().describe("Units in stock (>= 0)."),
  image_url: z7.string().url().nullable().optional().describe("Image URL, or null."),
  datasheet_url: z7.string().url().nullable().optional().describe("Datasheet URL, or null."),
  datasheet_name: text.nullable().optional().describe("Datasheet display name, or null.")
};
var PRODUCT_COLUMNS = "id, sku, name_ar, name_en, name_data, desc_ar, desc_en, brand, category_id, subcategory, price_iqd, price_wholesale_iqd, price_dealer_iqd, stock, is_active, image_url, datasheet_url, datasheet_name, created_at, updated_at";
function toProduct(p) {
  return {
    id: p.id,
    sku: p.sku ?? null,
    nameAr: p.name_ar,
    nameEn: p.name_en,
    nameData: p.name_data ?? null,
    descAr: p.desc_ar ?? null,
    descEn: p.desc_en ?? null,
    brand: p.brand ?? null,
    categoryId: p.category_id ?? null,
    subcategory: p.subcategory ?? null,
    priceIqd: p.price_iqd,
    priceWholesaleIqd: p.price_wholesale_iqd,
    priceDealerIqd: p.price_dealer_iqd,
    stock: p.stock,
    isActive: p.is_active,
    imageUrl: p.image_url ?? null,
    datasheetUrl: p.datasheet_url ?? null,
    datasheetName: p.datasheet_name ?? null,
    createdAt: p.created_at,
    updatedAt: p.updated_at
  };
}

// src/lib/mcp/tools/list-all-products.ts
var list_all_products_default = defineTool8({
  name: "list_all_products",
  title: "List all products (admin)",
  description: "Admin only. List products including hidden (inactive) ones, newest first. Filter by text, brand, category or active state.",
  inputSchema: {
    query: z8.string().trim().nullable().describe("Free text to match against names, SKU or brand, or null."),
    brand: z8.string().trim().nullable().describe("Exact brand name filter, or null."),
    category_id: z8.string().uuid().nullable().describe("Category id filter, or null."),
    is_active: z8.boolean().nullable().describe("true = only visible, false = only hidden, null = both."),
    limit: z8.number().int().min(1).max(200).nullable().describe("Maximum rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ query, brand, category_id, is_active, limit }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    let q = supabase.from("products").select(PRODUCT_COLUMNS).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (query) {
      const like = `%${query}%`;
      q = q.or(`name_ar.ilike.${like},name_en.ilike.${like},name_data.ilike.${like},sku.ilike.${like},brand.ilike.${like}`);
    }
    if (brand) q = q.eq("brand", brand);
    if (category_id) q = q.eq("category_id", category_id);
    if (is_active !== null) q = q.eq("is_active", is_active);
    const { data, error } = await q;
    if (error) throw new ToolError9(error.message);
    const products = (data ?? []).map(toProduct);
    return jsonResult(`${products.length} product(s).`, { products });
  }
});

// src/lib/mcp/tools/create-product.ts
import { defineTool as defineTool9, ToolError as ToolError10 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z9 } from "npm:zod@^3.25.76";
var create_product_default = defineTool9({
  name: "create_product",
  title: "Create product",
  description: "Admin only. Create a new product. New products are hidden (is_active=false) unless is_active is set, so they can be reviewed first.",
  inputSchema: {
    name_ar: z9.string().trim().min(1).describe("Arabic name (required)."),
    ...productFields,
    is_active: z9.boolean().optional().describe("Show on the store. Defaults to false.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const { data, error } = await supabase.from("products").insert({
      ...compact(input),
      name_en: input.name_en ?? input.name_ar,
      is_active: input.is_active ?? false
    }).select(PRODUCT_COLUMNS).single();
    if (error) throw new ToolError10(error.message);
    const product = toProduct(data);
    return jsonResult(`Product created (${product.id}).`, { product });
  }
});

// src/lib/mcp/tools/update-product.ts
import { defineTool as defineTool10, ToolError as ToolError11 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z10 } from "npm:zod@^3.25.76";
var update_product_default = defineTool10({
  name: "update_product",
  title: "Update product",
  description: "Admin only. Update a product. Only the fields provided are changed; pass null to clear an optional field.",
  inputSchema: {
    id: z10.string().uuid().describe("Product id."),
    name_ar: z10.string().trim().min(1).optional().describe("Arabic name."),
    ...productFields,
    is_active: z10.boolean().optional().describe("Show (true) or hide (false) on the store.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, ...fields }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const patch = compact(fields);
    assertHasChanges(patch);
    const { data, error } = await supabase.from("products").update(patch).eq("id", id).select(PRODUCT_COLUMNS).maybeSingle();
    if (error) throw new ToolError11(error.message);
    if (!data) notFound("product", id);
    const product = toProduct(data);
    return jsonResult(`Product updated (${product.id}).`, { product });
  }
});

// src/lib/mcp/tools/set-product-active.ts
import { defineTool as defineTool11, ToolError as ToolError12 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z11 } from "npm:zod@^3.25.76";
var set_product_active_default = defineTool11({
  name: "set_product_active",
  title: "Show or hide product",
  description: "Admin only. Show (is_active=true) or hide (is_active=false) a product on the store.",
  inputSchema: {
    id: z11.string().uuid().describe("Product id."),
    is_active: z11.boolean().describe("true to show on the store, false to hide.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, is_active }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const { data, error } = await supabase.from("products").update({ is_active }).eq("id", id).select(PRODUCT_COLUMNS).maybeSingle();
    if (error) throw new ToolError12(error.message);
    if (!data) notFound("product", id);
    const product = toProduct(data);
    return jsonResult(`Product ${is_active ? "shown" : "hidden"} (${product.id}).`, { product });
  }
});

// src/lib/mcp/tools/update-product-stock.ts
import { defineTool as defineTool12, ToolError as ToolError13 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z12 } from "npm:zod@^3.25.76";
var MAX_ATTEMPTS = 3;
var update_product_stock_default = defineTool12({
  name: "update_product_stock",
  title: "Update product stock",
  description: "Admin only. Set a product's stock to an absolute value (stock) or adjust it by a signed amount (delta). Provide exactly one. Stock can never go below 0.",
  inputSchema: {
    id: z12.string().uuid().describe("Product id."),
    stock: z12.number().int().min(0).optional().describe("New absolute stock (>= 0)."),
    delta: z12.number().int().optional().describe("Amount to add (positive) or remove (negative).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ id, stock, delta }, ctx) => {
    if (stock === void 0 === (delta === void 0)) throw new ToolError13("Provide exactly one of stock or delta");
    const { supabase } = await requireAdmin(ctx);
    if (stock !== void 0) {
      const { data, error } = await supabase.from("products").update({ stock }).eq("id", id).select(PRODUCT_COLUMNS).maybeSingle();
      if (error) throw new ToolError13(error.message);
      if (!data) notFound("product", id);
      const product = toProduct(data);
      return jsonResult(`Stock set to ${product.stock}.`, { product });
    }
    for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
      const { data: current, error: readError } = await supabase.from("products").select("stock").eq("id", id).maybeSingle();
      if (readError) throw new ToolError13(readError.message);
      if (!current) notFound("product", id);
      const next = current.stock + delta;
      if (next < 0) throw new ToolError13(`Stock cannot go below 0 (current ${current.stock}, delta ${delta})`);
      const { data, error } = await supabase.from("products").update({ stock: next }).eq("id", id).eq("stock", current.stock).select(PRODUCT_COLUMNS).maybeSingle();
      if (error) throw new ToolError13(error.message);
      if (data) {
        const product = toProduct(data);
        return jsonResult(`Stock changed from ${current.stock} to ${product.stock}.`, { product });
      }
    }
    throw new ToolError13("Stock changed concurrently; please retry");
  }
});

// src/lib/mcp/tools/delete-product.ts
import { defineTool as defineTool13, ToolError as ToolError14 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z13 } from "npm:zod@^3.25.76";
var delete_product_default = defineTool13({
  name: "delete_product",
  title: "Delete product",
  description: "Admin only. Permanently delete a product. Refused if the product appears in any order; use set_product_active with is_active=false to hide it instead.",
  inputSchema: { id: z13.string().uuid().describe("Product id.") },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const { count, error: countError } = await supabase.from("order_items").select("id", { count: "exact", head: true }).eq("product_id", id);
    if (countError) throw new ToolError14(countError.message);
    if ((count ?? 0) > 0) {
      throw new ToolError14(
        `Product appears in ${count} order item(s) and cannot be deleted. Use set_product_active with is_active=false to hide it instead.`
      );
    }
    const { data, error } = await supabase.from("products").delete().eq("id", id).select("id, name_ar, name_en").maybeSingle();
    if (error) throw new ToolError14(error.message);
    if (!data) notFound("product", id);
    const deleted = { id: data.id, nameAr: data.name_ar, nameEn: data.name_en };
    return jsonResult(`Product deleted (${deleted.id}).`, { deleted });
  }
});

// src/lib/mcp/tools/set-product-datasheet.ts
import { defineTool as defineTool14, ToolError as ToolError15 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z14 } from "npm:zod@^3.25.76";
var BUCKET = "product-images";
var FOLDER = "datasheets";
var MAX_BYTES = 10 * 1024 * 1024;
var FETCH_TIMEOUT_MS = 2e4;
function isPdf(bytes) {
  return bytes.length > 5 && String.fromCharCode(...bytes.subarray(0, 5)) === "%PDF-";
}
function decodeBase64(input) {
  const clean = input.replace(/^data:application\/pdf;base64,/, "").replace(/\s+/g, "");
  let binary;
  try {
    binary = atob(clean);
  } catch {
    throw new ToolError15("pdf_base64 is not valid base64");
  }
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}
async function download(url) {
  const res = await fetch(url, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) }).catch((e) => {
    throw new ToolError15(`Could not download the PDF: ${e.message}`);
  });
  if (!res.ok || !res.body) throw new ToolError15(`Could not download the PDF (HTTP ${res.status})`);
  const declared = Number(res.headers.get("content-length") ?? 0);
  if (declared > MAX_BYTES) throw new ToolError15("PDF is larger than 10 MB");
  const chunks = [];
  let total = 0;
  const reader = res.body.getReader();
  for (; ; ) {
    const { done, value } = await reader.read();
    if (done) break;
    total += value.length;
    if (total > MAX_BYTES) {
      await reader.cancel();
      throw new ToolError15("PDF is larger than 10 MB");
    }
    chunks.push(value);
  }
  const bytes = new Uint8Array(total);
  let offset = 0;
  for (const c of chunks) {
    bytes.set(c, offset);
    offset += c.length;
  }
  return bytes;
}
function fileNameFromUrl(url) {
  const last = decodeURIComponent(new URL(url).pathname.split("/").pop() ?? "");
  return last.toLowerCase().endsWith(".pdf") ? last : "datasheet.pdf";
}
function ownStoragePath(url) {
  if (!url) return null;
  const marker = `/storage/v1/object/public/${BUCKET}/`;
  const i = url.indexOf(marker);
  if (i === -1) return null;
  const path = url.slice(i + marker.length);
  return path.startsWith(`${FOLDER}/`) ? path : null;
}
var set_product_datasheet_default = defineTool14({
  name: "set_product_datasheet",
  title: "Set product datasheet (PDF)",
  description: "Admin only. Attach a PDF datasheet to a product (the '\u0648\u0631\u0642\u0629 \u0627\u0644\u0628\u064A\u0627\u0646\u0627\u062A (PDF)' field), replacing any existing one, or remove it. Provide exactly one of: pdf_url (an https link to a PDF; it is downloaded and stored on the site), pdf_base64 (the PDF file content), or remove=true. Max 10 MB.",
  inputSchema: {
    id: z14.string().uuid().describe("Product id."),
    pdf_url: z14.string().url().startsWith("https://").optional().describe("https URL of the PDF to download and attach."),
    pdf_base64: z14.string().min(1).optional().describe("Base64-encoded PDF file content."),
    file_name: z14.string().trim().min(1).max(200).optional().describe("Name shown to customers, e.g. 'TL-SG1008D.pdf'."),
    remove: z14.boolean().optional().describe("true to remove the product's datasheet.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ id, pdf_url, pdf_base64, file_name, remove }, ctx) => {
    const sources = [pdf_url, pdf_base64, remove ? true : void 0].filter((v) => v !== void 0);
    if (sources.length !== 1) throw new ToolError15("Provide exactly one of pdf_url, pdf_base64, or remove=true");
    const { supabase } = await requireAdmin(ctx);
    const { data: current, error: readError } = await supabase.from("products").select("id, datasheet_url").eq("id", id).maybeSingle();
    if (readError) throw new ToolError15(readError.message);
    if (!current) notFound("product", id);
    const previousPath = ownStoragePath(current.datasheet_url);
    let datasheetUrl = null;
    let datasheetName = null;
    let uploadedPath = null;
    if (!remove) {
      const bytes = pdf_url ? await download(pdf_url) : decodeBase64(pdf_base64);
      if (bytes.length > MAX_BYTES) throw new ToolError15("PDF is larger than 10 MB");
      if (!isPdf(bytes)) throw new ToolError15("The file is not a PDF");
      uploadedPath = `${FOLDER}/${id}-${crypto.randomUUID()}.pdf`;
      const { error: uploadError } = await supabase.storage.from(BUCKET).upload(uploadedPath, bytes, {
        contentType: "application/pdf",
        upsert: false,
        cacheControl: "31536000"
      });
      if (uploadError) throw new ToolError15(`Upload failed: ${uploadError.message}`);
      datasheetUrl = supabase.storage.from(BUCKET).getPublicUrl(uploadedPath).data.publicUrl;
      datasheetName = file_name ?? (pdf_url ? fileNameFromUrl(pdf_url) : "datasheet.pdf");
    }
    const { data, error } = await supabase.from("products").update({ datasheet_url: datasheetUrl, datasheet_name: datasheetName }).eq("id", id).select(PRODUCT_COLUMNS).maybeSingle();
    if (error || !data) {
      if (uploadedPath) await supabase.storage.from(BUCKET).remove([uploadedPath]);
      if (error) throw new ToolError15(error.message);
      notFound("product", id);
    }
    if (previousPath && previousPath !== uploadedPath) await supabase.storage.from(BUCKET).remove([previousPath]);
    const product = toProduct(data);
    return jsonResult(remove ? "Datasheet removed." : `Datasheet attached: ${product.datasheetName}.`, { product });
  }
});

// src/lib/mcp/tools/create-category.ts
import { defineTool as defineTool15, ToolError as ToolError16 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z15 } from "npm:zod@^3.25.76";
var create_category_default = defineTool15({
  name: "create_category",
  title: "Create category",
  description: "Admin only. Create a product category.",
  inputSchema: {
    name_ar: z15.string().trim().min(1).describe("Arabic name."),
    name_en: z15.string().trim().min(1).describe("English name."),
    key: z15.string().trim().min(1).optional().describe("Unique key (a-z, 0-9, dashes). Defaults to a slug of name_en."),
    sort: z15.number().int().min(0).optional().describe("Display order. Defaults to last.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ name_ar, name_en, key, sort }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const finalKey = slugify(key ?? name_en);
    if (!finalKey) throw new ToolError16("Could not derive a key from name_en; provide key explicitly");
    let finalSort = sort;
    if (finalSort === void 0) {
      const { count, error: error2 } = await supabase.from("categories").select("id", { count: "exact", head: true });
      if (error2) throw new ToolError16(error2.message);
      finalSort = count ?? 0;
    }
    const { data, error } = await supabase.from("categories").insert({ name_ar, name_en, key: finalKey, sort: finalSort }).select("id, key, name_ar, name_en, sort").single();
    if (error) throw new ToolError16(error.message);
    const category = { id: data.id, key: data.key, nameAr: data.name_ar, nameEn: data.name_en, sort: data.sort };
    return jsonResult(`Category created (${category.id}).`, { category });
  }
});

// src/lib/mcp/tools/update-category.ts
import { defineTool as defineTool16, ToolError as ToolError17 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z16 } from "npm:zod@^3.25.76";
var update_category_default = defineTool16({
  name: "update_category",
  title: "Update category",
  description: "Admin only. Update a product category. Only the fields provided are changed.",
  inputSchema: {
    id: z16.string().uuid().describe("Category id."),
    name_ar: z16.string().trim().min(1).optional().describe("Arabic name."),
    name_en: z16.string().trim().min(1).optional().describe("English name."),
    key: z16.string().trim().min(1).optional().describe("Unique key (a-z, 0-9, dashes)."),
    sort: z16.number().int().min(0).optional().describe("Display order.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, key, ...fields }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const patch = compact({ ...fields, key: key === void 0 ? void 0 : slugify(key) });
    if (patch.key === "") throw new ToolError17("key must contain letters or digits");
    assertHasChanges(patch);
    const { data, error } = await supabase.from("categories").update(patch).eq("id", id).select("id, key, name_ar, name_en, sort").maybeSingle();
    if (error) throw new ToolError17(error.message);
    if (!data) notFound("category", id);
    const category = { id: data.id, key: data.key, nameAr: data.name_ar, nameEn: data.name_en, sort: data.sort };
    return jsonResult(`Category updated (${category.id}).`, { category });
  }
});

// src/lib/mcp/tools/create-subcategory.ts
import { defineTool as defineTool17, ToolError as ToolError18 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z17 } from "npm:zod@^3.25.76";
var create_subcategory_default = defineTool17({
  name: "create_subcategory",
  title: "Create subcategory",
  description: "Admin only. Create a subcategory under an existing category.",
  inputSchema: {
    category_id: z17.string().uuid().describe("Parent category id."),
    name_ar: z17.string().trim().min(1).describe("Arabic name."),
    name_en: z17.string().trim().min(1).describe("English name.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const { data, error } = await supabase.from("subcategories").insert(input).select("id, category_id, name_ar, name_en").single();
    if (error) throw new ToolError18(error.message);
    const subcategory = { id: data.id, categoryId: data.category_id, nameAr: data.name_ar, nameEn: data.name_en };
    return jsonResult(`Subcategory created (${subcategory.id}).`, { subcategory });
  }
});

// src/lib/mcp/tools/update-subcategory.ts
import { defineTool as defineTool18, ToolError as ToolError19 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z18 } from "npm:zod@^3.25.76";
var update_subcategory_default = defineTool18({
  name: "update_subcategory",
  title: "Update subcategory",
  description: "Admin only. Rename a subcategory or move it to another category. Only the fields provided are changed.",
  inputSchema: {
    id: z18.string().uuid().describe("Subcategory id."),
    category_id: z18.string().uuid().optional().describe("New parent category id."),
    name_ar: z18.string().trim().min(1).optional().describe("Arabic name."),
    name_en: z18.string().trim().min(1).optional().describe("English name.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, ...fields }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const patch = compact(fields);
    assertHasChanges(patch);
    const { data, error } = await supabase.from("subcategories").update(patch).eq("id", id).select("id, category_id, name_ar, name_en").maybeSingle();
    if (error) throw new ToolError19(error.message);
    if (!data) notFound("subcategory", id);
    const subcategory = { id: data.id, categoryId: data.category_id, nameAr: data.name_ar, nameEn: data.name_en };
    return jsonResult(`Subcategory updated (${subcategory.id}).`, { subcategory });
  }
});

// src/lib/mcp/tools/create-brand.ts
import { defineTool as defineTool19, ToolError as ToolError20 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z19 } from "npm:zod@^3.25.76";

// src/lib/mcp/brands.ts
var BRAND_COLUMNS = "id, name, slug, description, logo_url, is_active, sort";
function toBrand(b) {
  return {
    id: b.id,
    name: b.name,
    slug: b.slug,
    description: b.description ?? null,
    logoUrl: b.logo_url ?? null,
    isActive: b.is_active,
    sort: b.sort
  };
}

// src/lib/mcp/tools/create-brand.ts
var create_brand_default = defineTool19({
  name: "create_brand",
  title: "Create brand",
  description: "Admin only. Create a brand.",
  inputSchema: {
    name: z19.string().trim().min(1).describe("Brand name."),
    slug: z19.string().trim().min(1).optional().describe("Unique URL slug. Defaults to a slug of name."),
    description: z19.string().trim().nullable().optional().describe("Description, or null."),
    logo_url: z19.string().url().nullable().optional().describe("Logo image URL, or null."),
    is_active: z19.boolean().optional().describe("Show on the store. Defaults to true."),
    sort: z19.number().int().min(0).optional().describe("Display order. Defaults to 0.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ name, slug, description, logo_url, is_active, sort }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const finalSlug = slugify(slug ?? name);
    if (!finalSlug) throw new ToolError20("Could not derive a slug from name; provide slug explicitly");
    const { data, error } = await supabase.from("brands").insert({
      name,
      slug: finalSlug,
      description: description ?? null,
      logo_url: logo_url ?? null,
      is_active: is_active ?? true,
      sort: sort ?? 0
    }).select(BRAND_COLUMNS).single();
    if (error) throw new ToolError20(error.message);
    const brand = toBrand(data);
    return jsonResult(`Brand created (${brand.id}).`, { brand });
  }
});

// src/lib/mcp/tools/update-brand.ts
import { defineTool as defineTool20, ToolError as ToolError21 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z20 } from "npm:zod@^3.25.76";
var update_brand_default = defineTool20({
  name: "update_brand",
  title: "Update brand",
  description: "Admin only. Update a brand. Only the fields provided are changed. Renaming does not update products.brand on existing products.",
  inputSchema: {
    id: z20.string().uuid().describe("Brand id."),
    name: z20.string().trim().min(1).optional().describe("Brand name."),
    slug: z20.string().trim().min(1).optional().describe("Unique URL slug."),
    description: z20.string().trim().nullable().optional().describe("Description, or null to clear."),
    logo_url: z20.string().url().nullable().optional().describe("Logo image URL, or null to clear."),
    is_active: z20.boolean().optional().describe("Show (true) or hide (false) on the store."),
    sort: z20.number().int().min(0).optional().describe("Display order.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, slug, ...fields }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const patch = compact({ ...fields, slug: slug === void 0 ? void 0 : slugify(slug) });
    if (patch.slug === "") throw new ToolError21("slug must contain letters or digits");
    assertHasChanges(patch);
    const { data, error } = await supabase.from("brands").update(patch).eq("id", id).select(BRAND_COLUMNS).maybeSingle();
    if (error) throw new ToolError21(error.message);
    if (!data) notFound("brand", id);
    const brand = toBrand(data);
    return jsonResult(`Brand updated (${brand.id}).`, { brand });
  }
});

// src/lib/mcp/tools/update-order-status.ts
import { defineTool as defineTool21, ToolError as ToolError22 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z21 } from "npm:zod@^3.25.76";
var ORDER_STATUSES = ["pending", "processing", "shipped", "delivered", "canceled"];
var update_order_status_default = defineTool21({
  name: "update_order_status",
  title: "Update order status",
  description: "Admin only. Change an order's status.",
  inputSchema: {
    id: z21.string().uuid().describe("Order id."),
    status: z21.enum(ORDER_STATUSES).describe("New status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const { data, error } = await supabase.from("orders").update({ status }).eq("id", id).select("id, order_no, status, updated_at").maybeSingle();
    if (error) throw new ToolError22(error.message);
    if (!data) notFound("order", id);
    const order = { id: data.id, orderNo: data.order_no, status: data.status, updatedAt: data.updated_at };
    return jsonResult(`Order ${order.orderNo} is now ${order.status}.`, { order });
  }
});

// src/lib/mcp/tools/update-quote-request-status.ts
import { defineTool as defineTool22, ToolError as ToolError23 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z22 } from "npm:zod@^3.25.76";
var QUOTE_STATUSES = ["new", "contacted", "closed"];
var update_quote_request_status_default = defineTool22({
  name: "update_quote_request_status",
  title: "Update quote request status",
  description: "Admin only. Change a quote request's status.",
  inputSchema: {
    id: z22.string().uuid().describe("Quote request id."),
    status: z22.enum(QUOTE_STATUSES).describe("New status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const { data, error } = await supabase.from("quote_requests").update({ status }).eq("id", id).select("id, full_name, status").maybeSingle();
    if (error) throw new ToolError23(error.message);
    if (!data) notFound("quote request", id);
    const quote = { id: data.id, fullName: data.full_name, status: data.status };
    return jsonResult(`Quote request ${quote.id} is now ${quote.status}.`, { quote });
  }
});

// src/lib/mcp/tools/create-blog-post.ts
import { defineTool as defineTool23, ToolError as ToolError24 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z24 } from "npm:zod@^3.25.76";

// src/lib/mcp/content.ts
import { z as z23 } from "npm:zod@^3.25.76";
var text2 = z23.string().trim();
var slugField = text2.min(1).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Use lowercase letters, digits and dashes only").describe("Unique URL slug (lowercase letters, digits, dashes).");
var blogFields = {
  title_ar: text2.min(1).describe("Arabic title."),
  title_en: text2.min(1).describe("English title."),
  excerpt_ar: text2.nullable().optional().describe("Arabic excerpt, or null."),
  excerpt_en: text2.nullable().optional().describe("English excerpt, or null."),
  body_ar: text2.nullable().optional().describe("Arabic body (HTML/Markdown as used on the site), or null."),
  body_en: text2.nullable().optional().describe("English body (HTML/Markdown as used on the site), or null."),
  cover_url: z23.string().url().nullable().optional().describe("Cover image URL, or null."),
  is_featured: z23.boolean().optional().describe("Feature on the home page."),
  featured_sort: z23.number().int().min(0).optional().describe("Order among featured posts.")
};
var BLOG_COLUMNS = "id, slug, title_ar, title_en, excerpt_ar, excerpt_en, cover_url, status, is_featured, featured_sort, published_at, created_at, updated_at";
function toBlogPost(p) {
  return {
    id: p.id,
    slug: p.slug,
    titleAr: p.title_ar,
    titleEn: p.title_en,
    excerptAr: p.excerpt_ar ?? null,
    excerptEn: p.excerpt_en ?? null,
    coverUrl: p.cover_url ?? null,
    status: p.status,
    isFeatured: p.is_featured,
    featuredSort: p.featured_sort,
    publishedAt: p.published_at ?? null,
    createdAt: p.created_at,
    updatedAt: p.updated_at
  };
}
var projectFields = {
  title_ar: text2.min(1).describe("Arabic title."),
  title_en: text2.min(1).describe("English title."),
  summary_ar: text2.nullable().optional().describe("Arabic summary, or null."),
  summary_en: text2.nullable().optional().describe("English summary, or null."),
  body_ar: text2.nullable().optional().describe("Arabic body, or null."),
  body_en: text2.nullable().optional().describe("English body, or null."),
  cover_url: z23.string().url().nullable().optional().describe("Cover image URL, or null."),
  gallery: z23.array(z23.string().url()).optional().describe("Gallery image URLs."),
  client: text2.nullable().optional().describe("Client name, or null."),
  location: text2.nullable().optional().describe("Location, or null."),
  completed_at: z23.string().date().nullable().optional().describe("Completion date (YYYY-MM-DD), or null."),
  sort: z23.number().int().min(0).optional().describe("Display order.")
};
var PROJECT_COLUMNS = "id, slug, title_ar, title_en, summary_ar, summary_en, cover_url, gallery, client, location, completed_at, is_published, sort, created_at, updated_at";
function toProject(p) {
  return {
    id: p.id,
    slug: p.slug,
    titleAr: p.title_ar,
    titleEn: p.title_en,
    summaryAr: p.summary_ar ?? null,
    summaryEn: p.summary_en ?? null,
    coverUrl: p.cover_url ?? null,
    gallery: p.gallery ?? [],
    client: p.client ?? null,
    location: p.location ?? null,
    completedAt: p.completed_at ?? null,
    isPublished: p.is_published,
    sort: p.sort,
    createdAt: p.created_at,
    updatedAt: p.updated_at
  };
}

// src/lib/mcp/tools/create-blog-post.ts
var create_blog_post_default = defineTool23({
  name: "create_blog_post",
  title: "Create blog post",
  description: "Admin only. Create a blog post. Saved as a draft unless status is 'published' (publishing notifies subscribed users).",
  inputSchema: {
    slug: slugField,
    ...blogFields,
    status: z24.enum(["draft", "published"]).optional().describe("Defaults to draft.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ status, ...fields }, ctx) => {
    const { supabase, userId } = await requireAdmin(ctx);
    const finalStatus = status ?? "draft";
    const { data, error } = await supabase.from("blog_posts").insert({
      ...compact(fields),
      status: finalStatus,
      author_id: userId,
      published_at: finalStatus === "published" ? (/* @__PURE__ */ new Date()).toISOString() : null
    }).select(BLOG_COLUMNS).single();
    if (error) throw new ToolError24(error.message);
    const post = toBlogPost(data);
    return jsonResult(`Blog post created as ${post.status} (${post.id}).`, { post });
  }
});

// src/lib/mcp/tools/update-blog-post.ts
import { defineTool as defineTool24, ToolError as ToolError25 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z25 } from "npm:zod@^3.25.76";
var update_blog_post_default = defineTool24({
  name: "update_blog_post",
  title: "Update blog post",
  description: "Admin only. Update a blog post. Only the fields provided are changed. Setting status to 'published' publishes it (and notifies subscribed users); 'draft' unpublishes it.",
  inputSchema: {
    id: z25.string().uuid().describe("Blog post id."),
    slug: slugField.optional(),
    title_ar: blogFields.title_ar.optional(),
    title_en: blogFields.title_en.optional(),
    excerpt_ar: blogFields.excerpt_ar,
    excerpt_en: blogFields.excerpt_en,
    body_ar: blogFields.body_ar,
    body_en: blogFields.body_en,
    cover_url: blogFields.cover_url,
    is_featured: blogFields.is_featured,
    featured_sort: blogFields.featured_sort,
    status: z25.enum(["draft", "published"]).optional().describe("draft or published.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status, ...fields }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const patch = compact(fields);
    if (status !== void 0) {
      const { data: current, error: error2 } = await supabase.from("blog_posts").select("published_at").eq("id", id).maybeSingle();
      if (error2) throw new ToolError25(error2.message);
      if (!current) notFound("blog post", id);
      patch.status = status;
      patch.published_at = status === "published" ? current.published_at ?? (/* @__PURE__ */ new Date()).toISOString() : null;
    }
    assertHasChanges(patch);
    const { data, error } = await supabase.from("blog_posts").update(patch).eq("id", id).select(BLOG_COLUMNS).maybeSingle();
    if (error) throw new ToolError25(error.message);
    if (!data) notFound("blog post", id);
    const post = toBlogPost(data);
    return jsonResult(`Blog post updated (${post.id}, ${post.status}).`, { post });
  }
});

// src/lib/mcp/tools/create-project.ts
import { defineTool as defineTool25, ToolError as ToolError26 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z26 } from "npm:zod@^3.25.76";
var create_project_default = defineTool25({
  name: "create_project",
  title: "Create project",
  description: "Admin only. Create a portfolio project. Unpublished unless is_published is true.",
  inputSchema: {
    slug: slugField,
    ...projectFields,
    is_published: z26.boolean().optional().describe("Show on the website. Defaults to false.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const { supabase, userId } = await requireAdmin(ctx);
    const { data, error } = await supabase.from("projects").insert({ ...compact(input), is_published: input.is_published ?? false, author_id: userId }).select(PROJECT_COLUMNS).single();
    if (error) throw new ToolError26(error.message);
    const project = toProject(data);
    return jsonResult(`Project created (${project.id}).`, { project });
  }
});

// src/lib/mcp/tools/update-project.ts
import { defineTool as defineTool26, ToolError as ToolError27 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z27 } from "npm:zod@^3.25.76";
var update_project_default = defineTool26({
  name: "update_project",
  title: "Update project",
  description: "Admin only. Update a portfolio project. Only the fields provided are changed.",
  inputSchema: {
    id: z27.string().uuid().describe("Project id."),
    slug: slugField.optional(),
    ...projectFields,
    title_ar: projectFields.title_ar.optional(),
    title_en: projectFields.title_en.optional(),
    is_published: z27.boolean().optional().describe("Show (true) or hide (false) on the website.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, ...fields }, ctx) => {
    const { supabase } = await requireAdmin(ctx);
    const patch = compact(fields);
    assertHasChanges(patch);
    const { data, error } = await supabase.from("projects").update(patch).eq("id", id).select(PROJECT_COLUMNS).maybeSingle();
    if (error) throw new ToolError27(error.message);
    if (!data) notFound("project", id);
    const project = toProject(data);
    return jsonResult(`Project updated (${project.id}).`, { project });
  }
});

// src/lib/mcp/index.ts
var projectRef = "ecbbhathvpxrgvfztzeu";
var mcp_default = defineMcp({
  name: "ufuk-al-basra",
  title: "UFUK AL-Basra",
  version: "0.3.0",
  instructions: 'Tools for the UFUK AL-Basra store. Use `search_products` and `get_product` for the catalog, `list_catalog_taxonomy` for categories and brands, `list_my_orders` and `get_order` for the signed-in user\'s orders, `create_quote_request` to ask sales for a price, and `list_content` for blog posts and projects. All data access runs as the signed-in user. Admin-only tools (they fail with "Admin role required" otherwise): `list_all_products` (includes hidden products); product writes `create_product`, `update_product`, `set_product_active`, `update_product_stock`, `set_product_datasheet` (attach/remove the PDF datasheet), `delete_product`; catalog writes `create_category`, `update_category`, `create_subcategory`, `update_subcategory`, `create_brand`, `update_brand`; `update_order_status`, `update_quote_request_status`; content writes `create_blog_post`, `update_blog_post`, `create_project`, `update_project`. Prefer hiding a product with `set_product_active` over deleting it.',
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_products_default,
    get_product_default,
    list_catalog_taxonomy_default,
    list_my_orders_default,
    get_order_default,
    create_quote_request_default,
    list_content_default,
    list_all_products_default,
    create_product_default,
    update_product_default,
    set_product_active_default,
    update_product_stock_default,
    delete_product_default,
    set_product_datasheet_default,
    create_category_default,
    update_category_default,
    create_subcategory_default,
    update_subcategory_default,
    create_brand_default,
    update_brand_default,
    update_order_status_default,
    update_quote_request_status_default,
    create_blog_post_default,
    update_blog_post_default,
    create_project_default,
    update_project_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
